[package]
name = "cell-model"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
rkyv = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
dirs = { workspace = true }