[package]
name = "ca"
version = "0.1.0"
edition = "2021"

[dependencies]
cell-sdk = { path = "../../cell-sdk" }
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
rcgen = "0.11"
time = "0.3"
rsa = "0.9"
pkcs8 = "0.10"
pem = "3.0"