[package]
name = "brain"
version = "0.3.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
cell-sdk = { path = "../../../../cell-sdk" }
cell-macros = { path = "../../../../cell-macros" }
bytemuck = "1.14"
