[package]
name = "coordinator"
version = "0.1.0"
edition = "2021"

[dependencies]
# cytosol = "0.2.0"
# ribosome = "0.2.0"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
tokio = { version = "1.36", features = ["full"] }

cytosol = { path = "../../../cytosol" }
ribosome = { path = "../../../ribosome" }
