[package]
name = "cell-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
cell-macros = { path = "../cell-macros" }
blake3 = "1.5"

[features]
build = []
