[package]
name = "cell-sdk"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
description = "Zero-copy RPC framework and runtime SDK."
repository = { workspace = true }

[features]
default = ["transport", "process", "axon"]
transport = ["dep:cell-transport"]
process = ["dep:cell-process"]
axon = ["dep:cell-axon"]

[dependencies]
cell-core = { workspace = true }
cell-model = { workspace = true }
cell-macros = { workspace = true }
cell-transport = { workspace = true, optional = true, features = ["std"] }
cell-axon = { workspace = true, optional = true }
cell-process = { workspace = true, optional = true }
cell-discovery = { workspace = true }

tokio = { workspace = true }
serde = { workspace = true }
rkyv = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
clap = { version = "4.5", features = ["derive"] }