[package]
name = "cell-sdk"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
description = "Zero-copy RPC framework and runtime SDK."
repository = { workspace = true }


[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.36", features = ["full"] }
rand = "0.8"
rkyv = { version = "0.7", features = ["validation"] }
memmap2 = "0.5"
nix = { version = "0.27", features = ["mman", "fs", "socket", "uio", "ioctl"] }
socket2 = { version = "0.5", features = ["all"] }
fd-lock = "4.0"
dirs = "5.0"
users = "0.11"
cell-macros = { path = "../cell-macros" }
blake3 = "1.5"
