[package]
name = "cell-sdk"
version = { workspace = true }
edition = { workspace = true }

[features]
default = []

[dependencies]
cell-core = { workspace = true }
cell-model = { workspace = true }
cell-macros = { workspace = true }

tokio = { workspace = true }
serde = { workspace = true }
rkyv = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
clap = { version = "4.5", features = ["derive"] }
dirs = { workspace = true }
rand = { workspace = true }
toml = "0.8"
blake3 = "1.5"
memmap2 = "0.5"
nix = { version = "0.27", features = ["fs", "mman", "signal"] }
