[package]
name = "cell-sdk"
version = "0.1.2"
edition = "2021"
authors = ["Leif Rydenfalk"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
humantime = "2.1"
lazy_static = "1.4"
blake3 = { version = "1.5", optional = true }
# Export rkyv for macros and downstream use
rkyv = { version = "0.7", features = ["validation"] }

cell-macros = { version = "0.1", path = "../cell-macros" }

[features]
default = []
build = ["blake3"]
