[package]
name = "cell-core"
version = { workspace = true }
edition = { workspace = true }
description = "The absolute minimum no_std primitives for Cell."

[dependencies]
# No standard library dependencies by default