[package]
name = "cell-build"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
convert_case = "0.6"
dirs = "5.0"