[workspace]
resolver = "2"
members = ["hello", "client"]

[workspace.dependencies]
# cell-sdk = { git = "https://github.com/Leif-Rydenfalk/cell", branch = "main" }

cell-sdk = { path = "../../cell-sdk" }
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
