[cell]
name = "coordinator"
binary = "target/release/coordinator"
schema = true

# The Router uses this to map names to paths locally
# If you were using a remote worker, you'd change this to an IP in the future.
[deps]
worker = "../worker"
aggregator = "../aggregator"
