[package]
name = "exchange"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
cell-sdk = { path = "../../../../cell-sdk" }
cell-macros = { path = "../../../../cell-macros" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
crc32fast = "1.3"