[package]
name = "cell-macros"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
description = "Procedural macros for Cell schemas."
repository = { workspace = true }

[lib]
proc-macro = true

[dependencies]
quote = { workspace = true }
syn = { workspace = true, features = ["full", "extra-traits", "parsing"] }
proc-macro2 = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = { workspace = true }
blake3 = { workspace = true }
rkyv = { workspace = true }
dirs = "5.0"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
