[package]
name = "cell-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "2", features = ["full", "parsing", "extra-traits"] }
proc-macro2 = "1"
serde_json = "1"
blake3 = "1.5"
