[package]
name = "consumer"
version = "0.1.0"
edition = "2021"

[dependencies]
cell-sdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }

[build-dependencies]
cell-sdk = { workspace = true, features = ["build"] }
blake3 = "1.5"
