[package]
name = "trader"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
cell-sdk = { path = "../../../../cell-sdk" }
cell-macros = { path = "../../../../cell-macros" }
crc32fast = "1.3"
rand = "0.8"
