[package]
name = "cell-cli"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
description = "The Cell Daemon and Orchestrator. Manages local nodes, cgroups, and mesh routing."
repository = { workspace = true }

[[bin]]
name = "cell"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
humantime = { workspace = true }
libc = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
clap = { workspace = true }
toml = { workspace = true }
bytes = { workspace = true }

# Target specific dependencies do not usually use { workspace = true } 
# unless you define them specifically in the root, but standard defining is fine here.
[target.'cfg(target_os = "linux")'.dependencies]
cgroups-rs = "0.3"
