[package]
name = "cell-cli"
version = "0.1.1"
edition = "2021"

[[bin]]
name = "cell"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
humantime = "2.1"
clap = { version = "4", features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
toml = "0.8"
walkdir = "2"
dirs = "5.0"
libc = "0.2"
blake3 = "1.5"
