[package]
name = "cell-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cell"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { version = "4", features = ["derive"] }
