[package]
name = "cell-cli"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
description = "The Cell Daemon and Orchestrator."
repository = { workspace = true }

[[bin]]
name = "cell"
path = "src/main.rs"

[lib]
name = "cell_cli"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
humantime = { workspace = true }
libc = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
clap = { workspace = true }
toml = { workspace = true }
bytes = { workspace = true }
snow = "0.9.6"
base64 = { workspace = true }
dirs = { workspace = true }
socket2 = "0.5"
rand = "0.8"
serde_json = "1.0"
regex = "1.10"

[target.'cfg(target_os = "linux")'.dependencies]
cgroups-rs = { workspace = true }
nix = { workspace = true }

[dev-dependencies]
tempfile = "3"
serial_test = "2.0"
