[package]
name = "firewall"
version = "0.1.0"
edition = "2021"

[dependencies]
cell-sdk = { path = "../../cell-sdk" }
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
ipnet = "2.9"
dashmap = "5.5"
serde = { version = "1.0", features = ["derive"] }
tracing-subscriber = "0.3" # Added to fix compilation error