[workspace]
members = [
    "bench-client",
    "bench-echo",
    "bench-processor",
    "calculator",
    "consumer",
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
cell-sdk = { path = "../cell-sdk" }
