[package]
name = "consensus"
version = "0.1.0"
edition = "2021"

[dependencies]
cell-sdk = { path = "../../cell-sdk" }
anyhow = { workspace = true }
tokio = { workspace = true, features = ["full"] }
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"
rand = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
rkyv = { workspace = true }
bincode = "1.3" # Efficient disk storage for WAL