[package]
name = "worker"
version = "0.1.0"
edition = "2021"

[dependencies]
# cytosol = "0.2.0"
# ribosome = "0.2.0"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
rand = "0.8"

# Uncomment this for local development if crates aren't published yet:
# [patch.crates-io]
cytosol = { path = "../../../cytosol" }
ribosome = { path = "../../../ribosome" }
