[package]
name = "registry"
version = "0.1.0"
edition = "2021"

[dependencies]
cell-sdk = { path = "../../cell-sdk" }
anyhow = { workspace = true }
tokio = { workspace = true }
dirs = { workspace = true }
tracing = { workspace = true }