[package]
name = "ledger"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
cell-sdk = { path = "../../../cell-sdk" }
cell-macros = { path = "../../../cell-macros" }
serde = { version = "1.0", features = ["derive"] }
dashmap = "5.5"
tracing = "0.1"
tracing-subscriber = "0.3"